adb shell pm disable-user --user 0 com.android.fmradio
adb shell pm disable-user --user 0 com.coloros.apprecover
adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox
adb shell pm disable-user --user 0 com.heytap.pictorial
adb shell pm disable-user --user 0 com.coloros.gamespace
adb shell pm disable-user --user 0 com.oppoex.afterservice
adb shell pm disable-user --user 0 com.oplus.onetrace
adb shell pm disable-user --user 0 com.coloros.athena
adb shell pm disable-user --user 0 com.coloros.blacklistapp
adb shell pm disable-user --user 0 com.oplus.eid
adb shell pm disable-user --user 0 com.android.nfc
adb shell pm disable-user --user 0 com.android.printspooler
adb shell pm disable-user --user 0 com.google.android.apps.wellbeing
adb shell pm disable-user --user 0 com.google.android.apps.nbu.files
adb shell pm disable-user --user 0 com.heytap.appplatform
adb shell pm disable-user --user 0 com.coloros.weather2
adb shell pm disable-user --user 0 com.google.android.feedback
adb shell pm disable-user --user 0 com.google.android.calendar
adb shell pm disable-user --user 0 com.oppo.sos
adb shell pm disable-user --user 0 com.tencent.soter.soterserver
adb shell pm disable-user --user 0 com.heytap.datamigration
adb shell pm disable-user --user 0 com.google.mainline.telemetry
adb shell pm disable-user --user 0 com.coloros.gamespaceui
adb shell pm disable-user --user 0 com.mediatek.voicecommand
adb shell pm disable-user --user 0 com.mediatek.gnssdebugreport
adb shell pm disable-user --user 0 com.coloros.phonemanager
adb shell pm disable-user --user 0 com.coloros.deepthinker
adb shell pm disable-user --user 0 com.heytap.mcs
adb shell pm disable-user --user 0 com.oppo.quicksearchbox
adb shell pm disable-user --user 0 com.mediatek.voiceunlock
adb shell pm disable-user --user 0 com.facebook.appmanager
adb shell pm disable-user --user 0 com.coloros.childrenspace
adb shell pm disable-user --user 0 com.android.traceur
adb shell pm disable-user --user 0 com.facebook.services
adb shell pm disable-user --user 0 com.facebook.system
